CREATE OR REPLACE TABLE CUSTOMER_DATA (
  CUSTOMER_ID NUMBER,
  NAME STRING,
  REGION STRING
);

INSERT INTO CUSTOMER_DATA VALUES
  (1, 'Alice', 'APAC'),
  (2, 'Bob', 'EMEA'),
  (3, 'Charlie', 'AMER');

  desc table  CUSTOMER_DATA